["repos/github.com/Lucioschenkel/lab"]
    type = "git-repo"
    url = "https://github.com/Lucioschenkel/lab.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/Lucioschenkel/config.nvim.git"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
